import type { RouteRecordRaw } from 'vue-router'

export const tenantLegacyRedirects: RouteRecordRaw[] = [
  { path: '/dashboard', redirect: '/' },
  { path: '/admin/collectors', redirect: '/admin/collector-connections' },
  { path: '/admin/capture-tasks', redirect: '/admin/collector-connections' },
  { path: '/admin/raw-capture-records', redirect: '/capture-records' },
  { path: '/admin/standard-details', redirect: '/waybill-batches' },
  { path: '/admin/field-definitions', redirect: '/admin/export-headers' },
  { path: '/admin/field-role-configs', redirect: '/admin/matching' },
  { path: '/admin/key-field-sets', redirect: '/admin/matching' },
  { path: '/admin/match-rules', redirect: '/admin/matching' },
  { path: '/admin/image-assets', redirect: '/admin/products' },
  { path: '/admin/report-batches', redirect: '/exports' },
  { path: '/admin/exceptions', redirect: '/exceptions' },
  { path: '/admin/export-records', redirect: '/exports' },
  { path: '/collectors', redirect: '/admin/collector-connections' },
  { path: '/capture-tasks', redirect: '/admin/collector-connections' },
  { path: '/raw-capture-records', redirect: '/capture-records' },
  { path: '/standard-details', redirect: '/waybill-batches' },
  { path: '/field-definitions', redirect: '/admin/export-headers' },
  { path: '/field-role-configs', redirect: '/admin/matching' },
  { path: '/key-field-sets', redirect: '/admin/matching' },
  { path: '/match-rules', redirect: '/admin/matching' },
  { path: '/image-assets', redirect: '/admin/products' },
  { path: '/stalls', redirect: '/admin/stalls' },
  { path: '/report-batches', redirect: '/exports' },
  { path: '/export-records', redirect: '/exports' },
]
