from app.models import (
    CaptureBatch,
    CaptureTask,
    Collector,
    ExceptionRecord,
    ExportRecord,
    FieldDefinition,
    FieldRoleConfig,
    ImageAsset,
    KeyFieldSet,
    MatchRule,
    OperationLog,
    PrintTemplateConfig,
    Product,
    ProductSku,
    RawCaptureRecord,
    ReportBatch,
    ReportLine,
    Role,
    Stall,
    StandardDetail,
    StandardDetailBatch,
    Tenant,
    User,
    WaybillMode,
    WaybillTemplate,
    WaybillTemplateField,
    Workspace,
)
from app.models.base import Base


RESOURCE_MODELS: dict[str, type[Base]] = {
    "tenants": Tenant,
    "workspaces": Workspace,
    "users": User,
    "roles": Role,
    "collectors": Collector,
    "capture_tasks": CaptureTask,
    "capture_batches": CaptureBatch,
    "raw_capture_records": RawCaptureRecord,
    "waybill_modes": WaybillMode,
    "waybill_templates": WaybillTemplate,
    "waybill_template_fields": WaybillTemplateField,
    "standard_detail_batches": StandardDetailBatch,
    "standard_details": StandardDetail,
    "field_definitions": FieldDefinition,
    "field_role_configs": FieldRoleConfig,
    "key_field_sets": KeyFieldSet,
    "match_rules": MatchRule,
    "products": Product,
    "product_skus": ProductSku,
    "stalls": Stall,
    "image_assets": ImageAsset,
    "report_batches": ReportBatch,
    "report_lines": ReportLine,
    "exception_records": ExceptionRecord,
    "export_records": ExportRecord,
    "operation_logs": OperationLog,
    "print_template_configs": PrintTemplateConfig,
}
